plugins {
    id 'com.android.application'
}

android {
    namespace 'com.example.qqmusicadblock'  // 👈 添加这一行！
    compileSdk 34

    defaultConfig {
        applicationId "com.example.qqmusicadblock"
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    lint {
        abortOnError false
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.6.1'
}
